### ISSUE TITLE
missing gem

### ISSUE THREAD

**Issue by sechix** [nebulab/solidus_shipwire#2]
Sorry, but when i try to install give e error due to missing gem

**Comment by DanielePalombo** [comment]
Could you paste the error message?

**Comment by sechix** [comment]
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Could not find gem 'solidus_shipwire' in any of the gem sources listed in your
Gemfile or available on this machine.


I have solidus 2.1.0.beta1 maybe its due to solidus version

**Comment by DanielePalombo** [comment]
try:

`gem 'solidus_shipwire', github: 'nebulab/solidus_shipwire'`

**Comment by sechix** [comment]
Yes, It works, thanks a lot!!!

**Comment by DanielePalombo** [comment]
Moved this extension to https://github.com/solidusio-contrib/solidus_shipwire. Now works with `gem 'solidus_shipwire'`
